# pillow-heif tests

This notebook contains some explorations with [pillow-heif](https://pillow-heif.readthedocs.io/en/latest/index.html)

In [12]:
from pathlib import Path

import numpy as np
import pillow_heif

SAMPLE_DATA_DIR = Path("/opt/dev/code-sprint-22-ngiis/GIMI Test Images")

In [11]:
sample1 = SAMPLE_DATA_DIR / "gimi_1_sentinel_hevc.heif"

print(f"HEIF file {str(sample1)!r}")
print(f"supported: {pillow_heif.is_supported(sample1)}")

heif_file = pillow_heif.open_heif(sample1)

print(f"Number of images contained in the file: {len(heif_file)}")

for index, img in enumerate(heif_file):
    print(f"image {index}: {img}") 

HEIF file '/opt/dev/code-sprint-22-ngiis/GIMI Test Images/gimi_1_sentinel_hevc.heif'
supported: True
Number of images contained in the file: 1
image 0: <HeifImage 342x342 RGB with no image data and 0 thumbnails>


### img.data

The `data` property of an image returns a [memoryview](https://docs.python.org/3/library/stdtypes.html#memoryview)

In [16]:
data_ = heif_file[0].data
print(type(data_))

<class 'memoryview'>


### Converting to a numpy array

`np.as_array` can be used to get a numpy array with the data too.

In [20]:
arr1 = np.asarray(heif_file[0])
print(arr1)

[[[ 86  96 108]
  [ 57  67  79]
  [ 43  53  65]
  ...
  [ 53  72  78]
  [ 49  68  74]
  [ 48  67  73]]

 [[ 56  66  78]
  [ 85  95 107]
  [ 88  98 110]
  ...
  [ 51  70  76]
  [ 50  69  75]
  [ 51  70  76]]

 [[ 81  87 101]
  [ 82  88 102]
  [ 81  87 101]
  ...
  [ 52  67  74]
  [ 55  70  77]
  [ 59  74  81]]

 ...

 [[ 36  43  59]
  [ 47  54  70]
  [ 71  78  94]
  ...
  [ 43  76  95]
  [ 44  75  93]
  [ 44  75  93]]

 [[ 63  70  86]
  [ 47  54  70]
  [ 38  45  61]
  ...
  [ 43  76  95]
  [ 44  75  95]
  [ 44  75  95]]

 [[ 41  48  64]
  [ 42  49  65]
  [ 59  66  82]
  ...
  [ 43  76  95]
  [ 44  75  95]
  [ 44  75  95]]]


### Inspecting metatada

Metadata seems to be shown by accessing the `info` property on one of the images. 

There does not seem to be a way to access general file-related metadata

In [21]:
heif_file[0].info

{'primary': True,
 'bit_depth': 8,
 'exif': None,
 'xmp': None,
 'metadata': [{'type': 'uri ',
   'content_type': '',
   'data': b"\x02\x08\x00\x06\x05c\xae'\xa9.\x03AS2A_MSIL1C_20230915T105701_N0509_R094_T30UYC_20230915T131504.SAFER\x04Jf\xf5\xbbS\x04\xff\xf3\xeaET\x04Jf\xf5\xbbU\x04\x01\x06\x86\x82V\x04H\xee\x16>W\x04\x01\x06\x86\x82X\x04H\xee\x16>Y\x04\xff\xf3\xeaEA\x01\x13\x01\x02n\xda"}],
 'thumbnails': [],
 'depth_images': []}

In [24]:
heif_file[0].info["metadata"][0]["data"]

b"\x02\x08\x00\x06\x05c\xae'\xa9.\x03AS2A_MSIL1C_20230915T105701_N0509_R094_T30UYC_20230915T131504.SAFER\x04Jf\xf5\xbbS\x04\xff\xf3\xeaET\x04Jf\xf5\xbbU\x04\x01\x06\x86\x82V\x04H\xee\x16>W\x04\x01\x06\x86\x82X\x04H\xee\x16>Y\x04\xff\xf3\xeaEA\x01\x13\x01\x02n\xda"

In [27]:
ba = bytearray(heif_file[0].info["metadata"][0]["data"])

In [30]:
chr?

Signature: chr(i, /)
Docstring: Return a Unicode string of one character with ordinal i; 0 <= i <= 0x10ffff.
Type:      builtin_function_or_method